services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\ServiceBw2\:
    resource: '../Classes/*'

  # To allow GeneralUtility::makeInstance
  JWeiland\ServiceBw2\Domain\Provider\ProviderFactory:
    public: true
    arguments:
      $providers: !tagged_iterator { tag: 'service-bw2.provider' }

  # To allow GeneralUtility::makeInstance
  JWeiland\ServiceBw2\Domain\Repository\RepositoryFactory:
    public: true
    arguments:
      $repositories: !tagged_iterator { tag: 'service-bw2.repository' }

  # TYPO3 extension solr might not be loaded. So, instantiation via GeneralUtility must be possible
  JWeiland\ServiceBw2\Service\SolrIndexService:
    autowire: false
    autoconfigure: false
    public: true

  # Will be called by GeneralUtility::makeInstance from FlexForm/TCA
  JWeiland\ServiceBw2\Tca\OrganisationseinheitenItems:
    public: true
